forum_ruby_version: "2.3.7"

COMMON_USING_INTERNAL_REPO: true
COMMON_ENABLE_DATADOG: False
COMMON_ENABLE_SPLUNKFORWARDER: True

###############################################################
#
#  Newrelic Settings
#
COMMON_ENABLE_NEWRELIC: True
COMMON_ENABLE_NEWRELIC_APP: True
COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE: true
NEWRELIC_LICENSE_KEY: '{{ COMMON_NEWRELIC_LICENSE }}'
NEWRELIC_API_KEY: '{{ COMMON_NEWRELIC_API_KEY }}'
NEWRELIC_INFRASTRUCTURE_LICENSE_KEY: '{{ NEWRELIC_LICENSE_KEY }}'

ENABLE_CLOUDPASSAGE: False
COMMON_DEPLOYMENT: "mckinsey"

# Apply security upgrades when we run ansible
SECURITY_UPGRADE_ON_ANSIBLE: true
COMMON_SECURITY_UPDATES: True

COMMON_EXTRA_CONFIGURATION_SOURCES_CHECKING: true
COMMON_EXTRA_CONFIGURATION_SOURCES:
  - "COMMON_USING_SECURE_REPO"
  - "COMMON_USING_INTERNAL_REPO"

# AWS settings
COMMON_AWS_SYNC: true
AWS_S3_LOGS: true
AWS_S3_LOGS_NOTIFY_EMAIL: "devops+mckinsey-{{ COMMON_ENVIRONMENT }}-s3-sync@edx.org"
AWS_S3_LOGS_FROM_EMAIL: "devops@edx.org"

###############################################################
#
#  Overrides for Newrelic
#
EDXAPP_NEWRELIC_CMS_APPNAME: "{{ COMMON_ENVIRONMENT}}-mckinsey-studio"
EDXAPP_NEWRELIC_LMS_APPNAME: "{{ COMMON_ENVIRONMENT}}-mckinsey-courses"
APROS_NEWRELIC_APPNAME: "{{ COMMON_ENVIRONMENT}}-mckinsey-apros"
NEWRELIC_ACCOUNT_ID: '631098'

NEW_RELIC_SERVER_ALERT_VARS:
  SERVER_ALERT_MAPPING:
    Production Servers:
      - "prod-mckinsey-courses"
      - "prod-mckinsey-apros"
      - "prod-mckinsey-forum"


_mentoring_xblock_settings:
  theme:
    package: "problem_builder"
    locations:
      - "public/themes/apros.css"
  options:
    pb_mcq_hide_previous_answer: true
    pb_hide_feedback_if_attempts_remain: true

MCKA_APROS_GUNICORN_EXTRA_CONF: 'preload_app = True'
MCKA_APROS_GUNICORN_MAX_REQUESTS: 1000
EDXAPP_LMS_MAX_REQ: 1000
EDXAPP_CMS_MAX_REQ: 1000
EDXAPP_MYSQL_CONN_MAX_AGE: 600

EDXAPP_PYTHON_SANDBOX: false

EDXAPP_EMAIL_BACKEND: "django_ses.SESBackend"
EDXAPP_DEFAULT_FROM_EMAIL: "staff@mckinseyacademy.com"
EDXAPP_DEFAULT_FEEDBACK_EMAIL: "staff@mckinseyacademy.com"
EDXAPP_SERVER_EMAIL: "devops+mckinsey-{{ COMMON_ENVIRONMENT }}@edx.org"
EDXAPP_TECH_SUPPORT_EMAIL: "support@mckinseyacademy.com"
EDXAPP_CONTACT_EMAIL: "staff@mckinseyacademy.com"
EDXAPP_BUGS_EMAIL: "support@mckinseyacademy.com"
EDXAPP_BULK_EMAIL_DEFAULT_FROM_EMAIL: "no-reply@mckinseyacademy.com"

COMMON_ENABLE_BASIC_AUTH: False

EDXAPP_PLATFORM_NAME: "McKinsey Academy"

EDXAPP_AGGREGATION_EXCLUDE_ROLES: ["observer", "assistant", "staff", "instructor"]

#remove CyberSource2
EDXAPP_CC_PROCESSOR:
  CyberSource:
    SHARED_SECRET: ""
    MERCHANT_ID: ""
    SERIAL_NUMBER: ""
    ORDERPAGE_VERSION: '7'
    PURCHASE_ENDPOINT: ""

MCKA_APROS_ALLOW_EMBED_URL:
  - "https://mckinseylearning.csod.com"
  - "https://mckinseylearning-pilot.csod.com"
  - "https://mckinseylearning-pilot2.csod.com"
  - "https://mckinseylearning-stg.csod.com"
  - "https://*.mckinsey.com"
  - "https://cloud.scorm.com"

EDXAPP_SCORM_PKG_STORAGE_DIR: "scorms"
EDXAPP_SCORM_PLAYER_LOCAL_STORAGE_ROOT: "staticfiles/scorm"

EDXAPP_XBLOCK_SETTINGS:
  mentoring: "{{ _mentoring_xblock_settings }}"
  poll:
    theme:
      - package: "poll"
      - locations: []
  OoyalaPlayerBlock:
    3PLAY_API_KEY: "{{ OOYALA_3PLAY_API_KEY }}"
    ENABLE_PLAYER_TOKEN: True
    PARTNER_CODE: "{{ OOYALA_PARTNER_CODE }}"
    API_KEY: "{{ OOYALA_API_KEY }}"
    API_SECRET_KEY: "{{ OOYALA_API_SECRET_KEY }}"
  group_project_v2:
     dashboard_details_url: "/admin/workgroup/dashboard/programs/{program_id}/courses/{course_id}/projects/{project_id}/details?activate_block_id={activity_id}"
     ta_review_url: "/courses/{course_id}/group_work/{group_id}?activate_block_id={activate_block_id}"
     access_dashboard_for_all_orgs_groups: ["mcka_role_mcka_admin"]
     access_dashboard_groups: ["mcka_role_client_admin", "mcka_role_internal_admin"]
     access_dashboard_ta_groups: ["mcka_role_mcka_ta"]
     ta_roles: ["assistant"]
  ScormXBlock:
    SCORM_PLAYER_LOCAL_STORAGE_ROOT: "{{ EDXAPP_SCORM_PLAYER_LOCAL_STORAGE_ROOT }}"
    SCORM_PLAYER_BACKENDS:
      ssla:
        name: "SSLA"
        location: "/static/scorm/ssla/player.htm"
        configuration: {}
    SCORM_PKG_STORAGE_DIR: "{{ EDXAPP_SCORM_PKG_STORAGE_DIR }}"

# Features configuration
EDXAPP_ENV_EXTRA:
    THIRD_PARTY_AUTH_FRAME_ALLOWED_FROM_URL: "{{ MCKA_APROS_ALLOW_EMBED_URL }}"
    REGISTRATION_EXTRA_FIELDS:
        level_of_education: 'optional'
        gender: 'optional'
        year_of_birth: 'optional'
        mailing_address: 'hidden'
        goals: 'hidden'
        honor_code: 'hidden'
        city: 'required'
        country: 'required'
    NOTIFICATION_CLICK_LINK_URL_MAPS:
        'open-edx.studio.announcements.*': "/courses/{course_id}/announcements"
        'open-edx.lms.leaderboard.*': "/courses/{course_id}/cohort"
        'open-edx.lms.discussions.*': "/courses/{course_id}/discussion/{commentable_id}/threads/{thread_id}"
        'open-edx.xblock.group-project.*': "/courses/{course_id}/group_work?seqid={activity_location}"
    NOTIFICATION_EMAIL_CLICK_LINK_URL_FORMAT: "https://{hostname}/notification_redir?redirect_path={url_path}&msg_id={msg_id}"
    NOTIFICATION_APP_HOSTNAME: "{{ APROS_ELB }}"
    NOTIFICATION_BRANDED_DEFAULT_LOGO: "/edx/app/edxapp/themes/mcka-theme/lms/static/images/McKAlogo.png"
    NOTIFICATION_DAILY_DIGEST_SUBJECT: "McKinsey Academy: Daily Notification Digest - {display_name}"
    NOTIFICATION_WEEKLY_DIGEST_SUBJECT: "McKinsey Academy: Weekly Notification Digest - {display_name}"
    NOTIFICATION_EMAIL_FROM_ADDRESS: "staff@mckinseyacademy.com"

    PASSWORD_MIN_LENGTH: 8
    PASSWORD_MAX_LENGTH: 128
    MINIMUM_PASSWORD_COMPLEXITY_SCORE: 5
    PASSWORD_COMPLEXITY:
        UPPER: 1
        LOWER: 1
        PUNCTUATION: 1
        DIGITS: 1
        UPPER_SCORE: 2
        LOWER_SCORE: 2
        PUNCTUATION_SCORE: 1
        DIGITS_SCORE: 1

    PASSWORD_DICTIONARY_EDIT_DISTANCE_THRESHOLD: !!null
    PASSWORD_DICTIONARY: []
    SESSION_COOKIE_DOMAIN: "{{ EDXAPP_SESSION_COOKIE_DOMAIN }}"
    XBLOCK_SELECT_FUNCTION: 'prefer_xmodules'
    X_FRAME_OPTIONS: 'SAMEORIGIN'
    GOOGLE_ANALYTICS_ACCOUNT_ID: "{{ GOOGLE_ANALYTICS_ACCOUNT_ID }}y"
    ADVANCED_SECURITY_CONFIG:
        MIN_DIFFERENT_STAFF_PASSWORDS_BEFORE_REUSE: 5
        MIN_DAYS_FOR_STAFF_ACCOUNTS_PASSWORD_RESETS: 90
    EDX_API_KEY: "{{ MCKA_APROS_API_KEY }}"
    SESSION_COOKIE_HTTPONLY: false
    SESSION_COOKIE_SECURE: true
    EXCLUDE_MIDDLEWARE_CLASSES: ["track.middleware.TrackMiddleware",
        "dark_lang.middleware.DarkLangMiddleware",
        "geoinfo.middleware.CountryMiddleware",
        "embargo.middleware.EmbargoMiddleware",
        "student.middleware.UserStandingMiddleware",
        "edxmako.middleware.MakoMiddleware"
      ]
    # Allow the mobile apps to determine whether a user is linked to an SSO
    # provider or not, for better login UX. This does allow anyone to query the
    # existence of accounts based on email or username, but that is considered
    # an acceptable tradeoff; most websites' registration forms leak that same info.
    ALLOW_UNPRIVILEGED_SSO_PROVIDER_QUERY: true
    # By default the completion ("progress") aggregation happens every time a user
    # completes an XBlock. This creates too much database activity for large
    # deployments, so we enable this setting to only compute aggregators
    # asyncronously using the hourly run_aggregator_service celery job.
    COMPLETION_AGGREGATOR_ASYNC_AGGREGATION: true
    RECALCULATE_SOCIAL_ENGAGEMENT_ROUTING_KEY: 'edx.lms.core.default'
    RATE_LIMIT_BACKEND_MAX_REQUESTS: 60


# Theme
EDXAPP_ENABLE_COMPREHENSIVE_THEMING: true
EDXAPP_COMPREHENSIVE_THEME_DIRS:
  - "/edx/app/edxapp/themes"
EDXAPP_DEFAULT_SITE_THEME: 'mcka-theme'
edxapp_theme_name: 'mcka-theme'
edxapp_theme_source_repo: 'git@github.com:mckinseyacademy/mcka-theme.git'
edxapp_theme_version: 'master'


SPLUNK_SSL_COMMON_NAME: splunk.edx.org

SPLUNKFORWARDER_DEB: 'splunkforwarder-7.2.3-06d57c595b80-linux-2.6-amd64.deb'
SPLUNKFORWARDER_PACKAGE_URL: "https://s3.amazonaws.com/edx-static/splunk_packages/a6b48bfe-c7a0-11e2-8e7f-e7082bf84480/{{ SPLUNKFORWARDER_DEB }}"


SPLUNKFORWARDER_SERVERS:
  - target_group: "new_splunk"
    server: "tools-edx-splunk-external-1804361693.us-east-1.elb.amazonaws.com:9995"
    default: true
    ssl_cert: "{{ SPLUNK_SSL_CERT }}"
    ssl_cert_password: "{{ SPLUNK_SSL_PASSWORD }}"
    ssl_root_ca: "{{ SPLUNK_SSL_ROOT_CA }}"
    ssl_common_name: "{{ SPLUNK_SSL_COMMON_NAME }}"

SPLUNKFORWARDER_LOG_ITEMS:
  - source: '{{ COMMON_LOG_DIR }}/lms'
    recursive: true
    index: '{{COMMON_ENVIRONMENT}}-{{COMMON_DEPLOYMENT}}'
    sourcetype: 'edx'
  - source: '{{ COMMON_LOG_DIR }}/cms'
    recursive: true
    index: '{{COMMON_ENVIRONMENT}}-{{COMMON_DEPLOYMENT}}'
    sourcetype: 'edx'
  - source: '{{ COMMON_LOG_DIR }}/mcka_apros'
    recursive: true
    index: '{{COMMON_ENVIRONMENT}}-{{COMMON_DEPLOYMENT}}'
    sourcetype: 'edx'
  - source: '{{ COMMON_LOG_DIR }}/supervisor'
    recursive: true
    index: '{{COMMON_ENVIRONMENT}}-{{COMMON_DEPLOYMENT}}'
    sourcetype: 'syslog'
  - source: '/var/log'
    recursive: true
    index: '{{COMMON_ENVIRONMENT}}-{{COMMON_DEPLOYMENT}}'
    sourcetype: 'syslog'
  - source: '{{ COMMON_LOG_DIR }}/nginx'
    recursive: true
    index: '{{COMMON_ENVIRONMENT}}-{{COMMON_DEPLOYMENT}}'
    sourcetype: 'nginx'
  - source: '{{ COMMON_LOG_DIR }}/ntp.log'
    recursive: false
    index: '{{COMMON_ENVIRONMENT}}-{{COMMON_DEPLOYMENT}}'
    sourcetype: 'edx'
  - source: '{{ COMMON_LOG_DIR }}/mongo'
    recursive: true
    index: '{{COMMON_ENVIRONMENT}}-{{COMMON_DEPLOYMENT}}'
    sourcetype: 'mongo'


NGINX_CMS_PROXY_CONNECT_TIMEOUT: '159s'
NGINX_CMS_PROXY_SEND_TIMEOUT: '600s'
NGINX_CMS_PROXY_READ_TIMEOUT: '600s'

SUPERVISOR_HIPCHAT_ROOM: 'Business.McKinsey'

# AIDE settings

AIDE_REPORT_EMAIL: devops+mckinsey@edx.org

EDXAPP_PROFILE_IMAGE_SIZES_MAP:
  full: 500
  large: 500
  medium: 160
  small: 48
EDXAPP_PROFILE_IMAGE_MAX_AGE: 31536000
EDXAPP_PROFILE_IMAGE_BACKEND:
  class: 'storages.backends.s3boto.S3BotoStorage'
  options:
    location: '/profile-images'
    bucket: '{{ AWS_STORAGE_BUCKET_NAME }}'
    custom_domain: '{{ AWS_STORAGE_BUCKET_NAME }}.s3.amazonaws.com'
    headers:
      Cache-Control: max-age-{{ EDXAPP_PROFILE_IMAGE_MAX_AGE }}
EDXAPP_ORGANIZATION_LOGO_IMAGE_BACKEND:
  class: 'storages.backends.s3boto.S3BotoStorage'
  options:
    location: '/organization-logo-images'
    bucket: '{{ AWS_STORAGE_BUCKET_NAME }}'
    custom_domain: '{{ AWS_STORAGE_BUCKET_NAME }}.s3.amazonaws.com'
    headers:
      Cache-Control: max-age-{{ EDXAPP_PROFILE_IMAGE_MAX_AGE }}
EDXAPP_PARENTAL_CONSENT_AGE_LIMIT: None

###############################################################
#
#  SAML settings
#
MCKA_APROS_SSO_AUTOPROVISION_PROVIDERS: ["saml-idp-mckinsey"]

# Feature Flags (sic)
MCKA_APROS_MILESTONES_ENABLED: false

##################################################################
#
# Internationalization settings
#
MCKA_APROS_ENABLE_INTERNATIONALIZATION : True
MCKA_APROS_SUPPORTED_LANGUAGES:
  en: English
  ar: العربية
  es: Español
  nl: Dutch
  pt: Português
  zh: 中文(简体)
  fr: Français
  de: Deutsch
  ja: 日本人

###############################################################
#
#  Mongo Settings
#
MONGO_VOLUMES:
  - device: /dev/xvdk
    mount: /edx/var/mongo
    options: "defaults,noatime"
    fstype: ext4
  - device: /dev/xvdj
    mount: /edx/var/mongo/mongodb/journal
    options: "defaults,noatime"
    fstype: ext4


EDXAPP_CELERY_WORKERS:
- concurrency: 5
  monitor: true
  queue: default
  service_variant: cms
  max_tasks_per_child: 5000
- concurrency: 1
  monitor: true
  queue: high
  service_variant: cms
  max_tasks_per_child: 5000
- concurrency: 4
  monitor: true
  queue: default
  service_variant: lms
  max_tasks_per_child: 5000
- concurrency: 4
  monitor: true
  queue: high
  service_variant: lms
  max_tasks_per_child: 5000
- concurrency: 2
  max_tasks_per_child: 1
  monitor: false
  queue: high_mem
  service_variant: lms
  max_tasks_per_child: 5000
- concurrency: 4
  monitor: true
  queue: completion_aggregator
  service_variant: lms
  max_tasks_per_child: 10000
