---
COMMON_ENVIRONMENT: "stage"
AWS_STORAGE_BUCKET_NAME: 'stage-group-work'
BASE_DOMAIN: "mckinsey.edx.org"

# SSH onto Stage
COMMON_USER_INFO:
  - name: e0d
    github: true
    type: admin
  - name: feanil
    github: true
    type: admin
  - name: jibsheet
    github: true
    type: admin
    state: absent
  - name: jarv
    github: true
    state: absent
  - name: maxrothman
    github: true
    state: absent
  - name: fredsmith
    github: true
    type: admin
  - name: jdmulloy
    github: true
    type: admin
  - name: coryleeio
    github: true
    type: admin
  - name: bderusha
    github: true
    type: admin
  - name: hkim823
    github: true
    state: absent
  - name: antoviaque
    github: true
    state: absent
  - name: e-kolpakov
    github: true
    state: absent
  - name: arbabnazar
    github: true
    state: absent
  - name: bilalahmad99
    github: true
    state: absent
  - name: michaelroytman
    github: true
    state: absent
  - name: nadeemshahzad
    github: true
    type: admin
  - name: syed-awais-ali
    github: true
    type: admin
  - name: ziafazal
    github: true
    type: admin
  - name: wajeeha-khalid
    github: true
    type: admin
  - name: msaqib52
    github: true
    type: admin
  - name: naeem91
    github: true
    type: admin
  - name: ihtram
    github: true
    type: admin

# ELB DNS
LMS_ELB: "courses.{{COMMON_ENVIRONMENT}}.{{BASE_DOMAIN}}"
CMS_ELB: "studio.{{COMMON_ENVIRONMENT}}.{{BASE_DOMAIN}}"
XQUEUE_ELB: "{{COMMON_ENVIRONMENT}}-xqueue.{{BASE_DOMAIN}}"
XSERVER_ELB: "{{COMMON_ENVIRONMENT}}-xserver.{{BASE_DOMAIN}}"
RABBIT_ELB: "{{COMMON_ENVIRONMENT}}-rabbit.{{BASE_DOMAIN}}"
FORUM_ELB: "{{COMMON_ENVIRONMENT}}-forum.{{BASE_DOMAIN}}"
APROS_ELB: "{{COMMON_ENVIRONMENT}}.{{BASE_DOMAIN}}"


# RDS DNS
RDS: "stage-mysql.{{BASE_DOMAIN}}"


ANTIVIRUS_BUCKETS:
  - 'stage-group-work'
ANTIVIRUS_MAILTO: "alerts@mckinseyacademy.com devops@edx.org"

# Edxapp Settings


EDXAPP_BASE: "{{BASE_DOMAIN}}"
EDXAPP_LMS_SUBDOMAIN: "{{COMMON_ENVIRONMENT}}"
EDXAPP_SESSION_COOKIE_DOMAIN: ".{{EDXAPP_LMS_SUBDOMAIN}}.{{EDXAPP_BASE}}"
EDXAPP_LMS_BASE: "{{EDXAPP_LMS_SUBDOMAIN}}.{{EDXAPP_BASE}}"
EDXAPP_PREVIEW_LMS_BASE: "preview.{{EDXAPP_LMS_BASE}}"
EDXAPP_SITE_NAME: "{{EDXAPP_LMS_BASE}}"
EDXAPP_CMS_BASE: "{{CMS_ELB}}"
EDXAPP_IMPORT_EXPORT_BUCKET: "{{ AWS_STORAGE_BUCKET_NAME }}"

EDXAPP_XQUEUE_URL: "http://{{XQUEUE_ELB}}"

EDXAPP_CMS_NGINX_PORT: "{{EDXAPP_LMS_NGINX_PORT}}"

EDXAPP_AWS_S3_CUSTOM_DOMAIN: "stage-group-work.s3.amazonaws.com"

MCKA_APROS_WORKERS: 5
EDXAPP_WORKERS:
  lms: 20
  cms: 3
EDXAPP_MYSQL_HOST: "{{RDS}}"
EDXAPP_MYSQL_DB_NAME: "edxapp"
EDXAPP_MYSQL_USER: "edxapp001"


EDXAPP_MONGO_DB_NAME: "prod"
EDXAPP_MONGO_HOSTS: "{{ MONGO_RS_CONFIG.members|map(attribute='host')|join(',') }}"
EDXAPP_MONGO_USER: "edxapp002"
EDXAPP_MONGO_PORT: 27017

EDXAPP_GRADE_STORAGE_CLASS: 'storages.backends.s3boto.S3BotoStorage'
EDXAPP_GRADE_STORAGE_KWARGS:
  bucket: "{{ AWS_STORAGE_BUCKET_NAME }}"
  custom_domain: null
  location: 'grades'
  querystring_expire: 300
  querystring_auth: true
  gzip: true
  default_acl: 'private'

EDXAPP_MEMCACHE:
  - "sta-ca-xj1uitwx5pod.kc0hii.0001.use1.cache.amazonaws.com:11211"
  - "sta-ca-xj1uitwx5pod.kc0hii.0002.use1.cache.amazonaws.com:11211"

EDXAPP_COMMENTS_SERVICE_URL: "https://{{FORUM_ELB}}"

EDXAPP_RABBIT_HOSTNAME: "{{RABBIT_ELB}}"

MCKA_APROS_BASIC_AUTH: false


# Features
EDXAPP_FEATURES:
  API: true
  AUTH_USE_OPENID_PROVIDER: true
  CERTIFICATES_ENABLED: true
  ENABLE_CORS_HEADERS: true
  ENABLE_DISCUSSION_SERVICE: true
  ENABLE_INSTRUCTOR_ANALYTICS: true
  SUBDOMAIN_BRANDING: false
  SUBDOMAIN_COURSE_LISTINGS: false
  PREVIEW_LMS_BASE: '{{ EDXAPP_PREVIEW_LMS_BASE }}'
  USE_CUSTOM_THEME: false
  PREVENT_CONCURRENT_LOGINS: false
  ENABLE_MAX_FAILED_LOGIN_ATTEMPTS: true
  ENFORCE_PASSWORD_POLICY: true
  USE_MICROSITES: false
  ALLOW_ALL_ADVANCED_COMPONENTS: true
  ALLOW_WIKI_ROOT_ACCESS: false
  SQUELCH_PII_IN_LOGS: true
  ENABLE_COURSEWARE_GOOGLE_ANALYTICS: true
  ADVANCED_SECURITY: true
  ENABLE_DISCUSSION_HOME_PANEL: true
  MARK_PROGRESS_ON_GRADING_EVENT: true
  ENABLE_DISCUSSION_EMAIL_DIGEST: true
  SIGNAL_ON_SCORE_CHANGED: true
  STUDENT_GRADEBOOK: true
  GRADEBOOK_APP: true
  STUDENT_PROGRESS: true
  PROGRESS_APP: true
  ORGANIZATIONS_APP: false
  PROJECTS_APP: true
  ALLOW_STUDENT_STATE_UPDATES_ON_CLOSED_COURSE: false
  ENABLE_NOTIFICATIONS: true
  ENABLE_SOCIAL_ENGAGEMENT: true
  ENABLE_XBLOCK_VIEW_ENDPOINT: true
  ENABLE_HTML_XBLOCK_STUDENT_VIEW_DATA: true
  ENABLE_THIRD_PARTY_AUTH: true
  ENABLE_CREATOR_GROUP: true
  ALLOW_PUBLIC_ACCOUNT_CREATION: false
  EDX_SOLUTIONS_API: true
  ENABLE_CSMH_EXTENDED: false
  DISPLAY_DEBUG_INFO_TO_STAFF: false
  CERTIFICATES_HTML_VIEW: true
  ENABLE_MOBILE_REST_API: true
  ENABLE_OAUTH2_PROVIDER: true
  ENABLE_COMBINED_LOGIN_REGISTRATION: true
  DISABLE_START_DATES: true
  MAX_PROBLEM_RESPONSES_COUNT: null


EDXAPP_LMS_AUTH_EXTRA:
    # DISABLE FOR NOW UNTIL WE CAN KEEP LMS SESSIONS REFRESHED
    #SESSION_INACTIVITY_TIMEOUT_IN_SECONDS: 1800
    EDX_API_KEY: "{{ MCKA_APROS_API_KEY }}"
    AWS_ACCESS_KEY_ID: "{{ EDXAPP_AUTH_AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ EDXAPP_AUTH_AWS_SECRET_ACCESS_KEY }}"
    DEFAULT_FILE_STORAGE: 'storages.backends.s3boto.S3BotoStorage'
    AWS_STORAGE_BUCKET_NAME: '{{ AWS_STORAGE_BUCKET_NAME }}'
    THIRD_PARTY_AUTH_CUSTOM_AUTH_FORMS:
      apros:
        secret_key: "{{ MCKA_APROS_THIRD_PARTY_AUTH_API_SECRET }}"
        url: "https://{{ APROS_ELB }}/accounts/finalize/"
        error_url: "https://{{ APROS_ELB }}/accounts/sso_error/"
        link_by_email: true
    MODULESTORE:
      default:
        ENGINE: 'xmodule.modulestore.mongo.MongoModuleStore'
        OPTIONS:
          collection:  'modulestore'
          db:  '{{ EDXAPP_MONGO_DB_NAME }}'
          default_class:  'xmodule.hidden_module.HiddenDescriptor'
          fs_root:  '{{ edxapp_course_data_dir }}'
          host: '{{ EDXAPP_MONGO_HOSTS }}'
          password:  '{{ EDXAPP_MONGO_PASSWORD }}'
          port: '{{ EDXAPP_MONGO_PORT }}'
          render_template:  'edxmako.shortcuts.render_to_string'
          # Needed for the CMS to be able to run update_templates
          user: '{{ EDXAPP_MONGO_USER }}'
        DOC_STORE_CONFIG:
          db: '{{ EDXAPP_MONGO_DB_NAME }}'
          host: '{{ EDXAPP_MONGO_HOSTS }}'
          password: '{{ EDXAPP_MONGO_PASSWORD }}'
          port: '{{ EDXAPP_MONGO_PORT }}'
          user: '{{ EDXAPP_MONGO_USER }}'
          collection:  'modulestore'
      direct:
        ENGINE: 'xmodule.modulestore.mongo.MongoModuleStore'
        OPTIONS:
          collection:  'modulestore'
          db:  '{{ EDXAPP_MONGO_DB_NAME }}'
          default_class:  'xmodule.hidden_module.HiddenDescriptor'
          fs_root:  '{{ edxapp_course_data_dir }}'
          host: '{{ EDXAPP_MONGO_HOSTS }}'
          password:  '{{ EDXAPP_MONGO_PASSWORD }}'
          port: '{{ EDXAPP_MONGO_PORT }}'
          render_template:  'edxmako.shortcuts.render_to_string'
          # Needed for the CMS to be able to run update_templates
          user: '{{ EDXAPP_MONGO_USER }}'
        DOC_STORE_CONFIG:
          db: '{{ EDXAPP_MONGO_DB_NAME }}'
          host: '{{ EDXAPP_MONGO_HOSTS }}'
          password: '{{ EDXAPP_MONGO_PASSWORD }}'
          port: '{{ EDXAPP_MONGO_PORT }}'
          user: '{{ EDXAPP_MONGO_USER }}'
          collection:  'modulestore'

EDXAPP_CMS_AUTH_EXTRA:
    # DISABLE FOR NOW UNTIL WE CAN KEEP LMS SESSIONS REFRESHED
    #SESSION_INACTIVITY_TIMEOUT_IN_SECONDS: 1800
    EDX_API_KEY: "{{ MCKA_APROS_API_KEY }}"
    AWS_ACCESS_KEY_ID: "{{ EDXAPP_AUTH_AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ EDXAPP_AUTH_AWS_SECRET_ACCESS_KEY }}"
    DEFAULT_FILE_STORAGE: 'storages.backends.s3boto.S3BotoStorage'
    AWS_STORAGE_BUCKET_NAME: '{{ AWS_STORAGE_BUCKET_NAME }}'
    MODULESTORE:
      default:
        ENGINE: 'xmodule.modulestore.mongo.DraftMongoModuleStore'
        OPTIONS:
          collection:  'modulestore'
          db:  '{{ EDXAPP_MONGO_DB_NAME }}'
          default_class:  'xmodule.hidden_module.HiddenDescriptor'
          fs_root:  '{{ edxapp_course_data_dir }}'
          host: '{{ EDXAPP_MONGO_HOSTS }}'
          password:  '{{ EDXAPP_MONGO_PASSWORD }}'
          port: '{{ EDXAPP_MONGO_PORT }}'
          render_template:  'edxmako.shortcuts.render_to_string'
          # Needed for the CMS to be able to run update_templates
          user: '{{ EDXAPP_MONGO_USER }}'
        DOC_STORE_CONFIG:
          db: '{{ EDXAPP_MONGO_DB_NAME }}'
          host: '{{ EDXAPP_MONGO_HOSTS }}'
          password: '{{ EDXAPP_MONGO_PASSWORD }}'
          port: '{{ EDXAPP_MONGO_PORT }}'
          user: '{{ EDXAPP_MONGO_USER }}'
          collection:  'modulestore'
      direct:
        ENGINE: 'xmodule.modulestore.mongo.MongoModuleStore'
        OPTIONS:
          collection:  'modulestore'
          db:  '{{ EDXAPP_MONGO_DB_NAME }}'
          default_class:  'xmodule.hidden_module.HiddenDescriptor'
          fs_root:  '{{ edxapp_course_data_dir }}'
          host: '{{ EDXAPP_MONGO_HOSTS }}'
          password:  '{{ EDXAPP_MONGO_PASSWORD }}'
          port: '{{ EDXAPP_MONGO_PORT }}'
          render_template:  'edxmako.shortcuts.render_to_string'
          # Needed for the CMS to be able to run update_templates
          user: '{{ EDXAPP_MONGO_USER }}'
        DOC_STORE_CONFIG:
          db: '{{ EDXAPP_MONGO_DB_NAME }}'
          host: '{{ EDXAPP_MONGO_HOSTS }}'
          password: '{{ EDXAPP_MONGO_PASSWORD }}'
          port: '{{ EDXAPP_MONGO_PORT }}'
          user: '{{ EDXAPP_MONGO_USER }}'
          collection:  'modulestore'


EDXAPP_CELERY_BROKER_TRANSPORT: 'redis'
EDXAPP_CELERY_BROKER_HOSTNAME: "mcka-stage-queues.kc0hii.ng.0001.use1.cache.amazonaws.com:6379"
EDXAPP_CELERY_BROKER_VHOST: 0
EDXAPP_CELERY_USER: ''

# edx-platform repo
edx_platform_repo: 'git@github.com:edx-solutions/edx-platform.git'
edx_platform_version: 'master'

# forum repo
forum_source_repo: 'https://github.com/edx-solutions/cs_comments_service.git'
forum_version: 'master'


# mckinsey academy apros repo
mcka_apros_source_repo: 'git@github.com:mckinseyacademy/mcka_apros.git'
mcka_apros_version: 'master'

# Use a temporary read-only SSH key to perform git checkouts
EDXAPP_USE_GIT_IDENTITY: true
MCKA_APROS_USE_GIT_IDENTITY: true
EDXAPP_CORS_ORIGIN_WHITELIST:
    - 'stage-beta.mckinsey.edx.org'
    - 'stage.mckinsey.edx.org'
    - 'login-npn-learn.mckinsey.com'
    - 'stage-group-work.s3.amazonaws.com'
    - 'mckidp.banpuindo.co.id'


MCKA_APROS_MYSQL_USER: "apros001"
MCKA_APROS_MYSQL_HOST: "{{RDS}}"
MCKA_APROS_MYSQL_DB_NAME: "mcka_apros"
MCKA_APROS_SESSION_COOKIE_DOMAIN: "{{EDXAPP_SESSION_COOKIE_DOMAIN}}"
MCKA_APROS_GA_TRACKING_ID: "UA-118894684-1"
MCKA_APROS_DJANGO_DEBUG: "False"


MONGO_S3_BACKUP: "true"
MONGO_S3_BACKUP_NODE: "stage-mongo-0.mckinsey.edx.org"
MONGO_S3_BACKUP_BUCKET: "edx-mckinsey-stage-backup"
MONGO_S3_NOTIFY_EMAIL: devops+mckinsey-stage-s3-sync@edx.org

MONGO_CLUSTERED: true
MONGO_REPL_SET: 'rs0'
MONGO_BIND_IP: 0.0.0.0
MONGO_RS_CONFIG:
    _id: '{{MONGO_REPL_SET}}'
    members:
        - host: '10.1.143.13'
        - host: '10.1.143.43'
        - host: '10.1.143.22'

APROS_CELERY_BROKER_HOSTNAME: "{{ RABBIT_ELB }}"

APROS_WORKER_LMS_BASE: "https://{{ LMS_ELB }}/"
APROS_WORKER_CMS_BASE: "https://{{ CMS_ELB }}/"

###############################################################
#
#  Overrides for Forum
#

FORUM_MONGO_USER: "comments002"
FORUM_MONGO_HOSTS: "{{ MONGO_RS_CONFIG.members|map(attribute='host')|list }}"
FORUM_MONGO_DATABASE: "prod-forum"
FORUM_MONGO_PORT: "27017"
FORUM_NEW_RELIC_APP_NAME: 'stage-mckinsey-forum'
FORUM_NEW_RELIC_LICENSE_KEY: "{{ NEWRELIC_LICENSE_KEY }}"
FORUM_NEW_RELIC_LOG: 'stdout'
FORUM_RACK_ENV: 'staging'
FORUM_SINATRA_ENV: 'staging'
FORUM_ELASTICSEARCH_HOST: "search-stage-mckinsey-forums-g7w7jybdcoknwhmkxk3hkar54e.us-east-1.es.amazonaws.com"
FORUM_ELASTICSEARCH_PROTOCOL: "https"
FORUM_ELASTICSEARCH_PORT: "443"

RABBIT_AUTOMATED_USERS:
  monitor:
    sudo_commands:
      - command: "/usr/sbin/service rabbitmq-server status"
      #on newer versions of rabbit, this doesn't have to be root.
        sudo_user: "root"
      - command: "/usr/sbin/rabbitmqctl cluster_status"
        sudo_user: "root"
    authorized_keys: "{{ MONITORING_AUTHORIZED_KEYS }}"

RABBITMQ_CLUSTERED: true
RABBITMQ_CLUSTERED_HOSTS:
  - "rabbit@ip-10-1-48-185"
  - "rabbit@ip-10-1-47-169"
  - "rabbit@ip-10-1-46-124"

RABBITMQ_VHOSTS:
  - '/'

###############################################################
#
#  Overrides for ElasticSearch
#
ELASTICSEARCH_CLUSTERED: true
ELASTICSEARCH_CLUSTER_MEMBERS:
  - 'ip-10-1-48-185'
  - 'ip-10-1-47-169'
  - 'ip-10-1-46-124'

###############################################################
#
#  Overrides for Newrelic
#
EDXAPP_NEWRELIC_CMS_APPNAME: 'stage-mckinsey-studio'
EDXAPP_NEWRELIC_LMS_APPNAME: 'stage-mckinsey-courses'
APROS_NEWRELIC_APPNAME: 'stage-mckinsey-apros'



MONITORING_AUTHORIZED_KEYS:
  - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACACY8P411/IHUK9gZBjn28rDlMbuncb1LdOGXXsd5Fmu2Zlg83XRXDfh6bR/gWqrIPA4Yf6CuCpZmi7x0X66PDemq1p+Dc1TviS4DeCsMlVJZ6eNBwg6NkQjgU1lROFhzWOvRcxLjUw/SfsiQFQ86jFEnTDRGZOW0aHGz8CYHjDjqKriDeZYDEQerg705e76Hoo1Q24WFczBN+yhiHetBNBwBefnRaLaq210xyIkt6tf1G9zKgeM7mWaOvTMpnujNOah5CrMs7wmsZ4EWMN1UB3O4AaeaMfigzzyih5kfN47ktXcBjSwlr1M9VDEvTmgFmW4dd8G8BHYz66S/r29KvyUBKthFfDPeEQLw/vqwHw6RGvITJyZH8w/oHLkI1ZniE43j4za82X0cO1P+vr2VeMpFG5XRkoa2c9HkqEPgZq79ssshILipkX+z4CBxPZv9EjxnxUwsNxhpFh5aECGldwRmQi4QyuEAQmeIcBfDIV2zditzlX9XK4lsfokcFF7ccvqXPFcSO6hZO9b8l67YxDZOHEJXwDTfcXpzxjmhMwBTmS47QT+7WeA7UyXfSmMepsv8AfC+FsCc7o/kc5RZMOz6mDDIm87CCs7NvEvjd7EnGV2l0mEK5SKSQQvvUHAOFbp+85WpAIKcdpHmQs3ZaX7dOwfJcDY5eMMhtIOCokCD automated+monitoring@edx.org'

##################################################################
#
# Enable Internationalization Flag
#
MCKA_APROS_ENABLE_INTERNATIONALIZATION : True


################################################
#
# Automated User configuration
#
#

EDXAPP_AUTOMATED_USERS:
  aggregation:
    sudo_commands:
      - command: "/edx/app/edxapp/venvs/edxapp/bin/python /edx/app/edxapp/edx-platform/manage.py lms run_aggregator_service --settings=aws --delay-between-batches 0.5 --routing-key=edx.lms.core.completion_aggregator"
        sudo_user: "www-data"
        job_name: "aggregator-update"
        schedule: "H * * * *"
      - command: "/edx/app/edxapp/venvs/edxapp/bin/python /edx/app/edxapp/edx-platform/manage.py lms run_aggregator_cleanup --settings=aws"
        sudo_user: "www-data"
        job_name: "aggregator-cleanup"
        schedule: "H * * * *"
    authorized_keys: "{{ EDXAPP_AGGREGATION_AUTHORIZED_KEYS }}"
  mckinsey_tasks:
    sudo_commands:
      - command: "/edx/bin/python.mcka_apros /edx/app/mcka_apros/mcka_apros/manage.py trigger_build_cache_task"
        sudo_user: "www-data"
        job_name: "build-apros-cache"
        schedule: "0 0 * * *"
      - command: "/edx/bin/python.mcka_apros /edx/app/mcka_apros/mcka_apros/manage.py purge_old_import_records"
        sudo_user: "www-data"
        job_name: "purge-import-records"
        schedule: "0 0 * * *"
      - command: "/edx/bin/python.mcka_apros /edx/app/mcka_apros/mcka_apros/manage.py load_seed_data --settings=mcka_apros.worker"
        sudo_user: "www-data"
        job_name: "load-seed-data"
      - command: "/edx/app/edxapp/venvs/edxapp/bin/python /edx/app/edxapp/edx-platform/manage.py lms compute_social_engagement_score -a true --noinput --settings=aws"
        sudo_user: "www-data"
        job_name: "compute-social-engagement-score"
      - command: "/edx/app/edxapp/venvs/edxapp/bin/python /edx/app/edxapp/edx-platform/manage.py lms compute_social_engagement_score --noinput --inactive true --months_back_limit 12 --settings=aws"
        sudo_user: "www-data"
        job_name: "update-closed-course-engagement-scores"
      - command: "/edx/app/edxapp/venvs/edxapp/bin/python /edx/app/edxapp/edx-platform/manage.py lms fix_empty_organization_attributes --settings=aws"
        sudo_user: "www-data"
        job_name: "fix-empty-organization-attributes"
      - command: "/edx/app/edxapp/venvs/edxapp/bin/python /edx/app/edxapp/edx-platform/manage.py lms background_notification_check --settings=aws"
        sudo_user: "www-data"
        job_name: "background-notification-check"
        schedule: "0 1 * * *"
      - command: "/edx/app/edxapp/venvs/edxapp/bin/python /edx/app/edxapp/edx-platform/manage.py lms reset_notification_timer --settings=aws"
        sudo_user: "www-data"
        job_name: "reset-notification-timer"
      - command: "/edx/bin/python.mcka_apros /edx/app/mcka_apros/mcka_apros/manage.py waffle_switch data_deletion.enable_data_deletion on --create"
        sudo_user: "www-data"
        job_name: "enable-data-deletion"
      - command: "/edx/bin/python.mcka_apros /edx/app/mcka_apros/mcka_apros/manage.py enable_new_ui_for_all_companies"
        sudo_user: "www-data"
        job_name: "enable-new-ui-for-all-companies"
      - command: "/edx/bin/python.mcka_apros /edx/app/mcka_apros/mcka_apros/manage.py deletion_admin add Ranji_Latchmansingh@mckinsey.com Nicolas_Carr@mckinsey.com Dale_Cook@mckinsey.com Pam_Lee@mckinsey.com"
        sudo_user: "www-data"
        job_name: "add-deletion-admins"
    authorized_keys: "{{ EDXAPP_MCKINSEY_MCKINSEY_TASKS_AUTHORIZED_KEYS }}"

# Automated configuration
# Key imported from mckinsey-secure/ansible/keys/automated
EDXAPP_AGGREGATION_AUTHORIZED_KEYS:
 - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCod8tjLYpN0jO8vrbb7MoxgkDhtr73ua08uf+QAU62Gb4bcAroA4CEtD5vVsK0pGHJn7aLLyadw/bpjmAZ0WRD6TeiYNy80MMSaiVpYaGSl+AEvEcdv6V9XMjKU/wMfSVTZnCSTb08XhwoehAJEuNOFFcGbzrabiPJy+z5BDyOWpJx8pQIdeasOK4LqRLOmwWhQRcu4Lcz1zu5j6jq7iQuSN4ZehT5G+1mNl68n1zDQUjy5Ds8KfaH3bYrBdetxeuQwcZXwezhWa63FtGvQlqJKYFxVaQJQdNTe6KeaFmoAZrQA2t3otubEpvdHs5E9kuPM5yBoXXFzNgi7kI7w2/l automated+aggregation@edx.org'
EDXAPP_MCKINSEY_MCKINSEY_TASKS_AUTHORIZED_KEYS:
  - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgZ4+vuReKTf5NV3SoaIkFDCuEjyEI2OsqIt8YeOOnF+OafgRT4Q7/z78RbrsbE4GlYR5e5IhXORKZmj/bFaX+IH0llp3vrHJNt+Xg0vSbr1WUkcNMKmLyJ6gw7m1TmNj1jInUy2mm22l+9cfOhMbPxneyvg8og62ydK94iJs9CPGGy6TCCV+Ek5lRX/R4txJ23A/vwt4xjahOz4RgTb6ZU+4tM7jIUGd8+JS9cQOp0P2jcffOqfCvgeK3i5TTtrNkc7oqgdyHcxxaOgpB7c44/4BtFEQRW9QsptpJqZh7r0VhBicgQGCgmmJMQzJoN6Z3E4jI0P8jMVf6UzUUkmab automated+mckinsey_tasks@edx.org'

# HEAP id for data analytics
HEAP_APP_ID: 2072626209
