---
# Versions of Python newer than 3.5 are not available in the default
# package index for Ubuntu 16.04. Add the deadsnakes PPA for anything
# newer
- name: add deadsnakes PPA for newer Python versions
  apt_repository:
    repo: "ppa:deadsnakes/ppa"
    update_cache: yes
  when: ansible_distribution_release == 'xenial'

# Install newer versions of python for testing, but do not set them
# as the default version
- name: Install python versions
  apt:
    name: 'python{{ item }}'
    state: present
    update_cache: yes
  with_items: '{{ jenkins_common_python_versions }}'

# Install 'dev' packages for each version of python that is installed
- name: Install python dev packages
  apt:
    name: 'python{{ item }}-dev'
    state: present
    update_cache: yes
  with_items: '{{ jenkins_common_python_versions }}'
