---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role hive
# 

HIVE_VERSION: 1.0.0
HIVE_HOME: "{{ HADOOP_COMMON_USER_HOME }}/hive"
HIVE_CONF: "{{ HIVE_HOME }}/conf"
HIVE_LIB: "{{ HIVE_HOME }}/lib"

#
# vars are namespace with the module name.
#
hive_role_name: hive
hive_temporary_dir: /var/tmp
hive_dist:
  filename: "apache-hive-{{ HIVE_VERSION }}-bin.tar.gz"
  url: "https://archive.apache.org/dist/hive/hive-{{ HIVE_VERSION }}/apache-hive-{{ HIVE_VERSION }}-bin.tar.gz"
  sha256sum: 4dab651288fee1d234e674efd3573a7441a8748e9a555e453999a75abc553b53

hive_site_config:
  javax.jdo.option.ConnectionURL: jdbc:derby:;databaseName=/var/tmp/metastore_db;create=true

#
# OS packages
#

hive_debian_pkgs: []

hive_redhat_pkgs: []
