prospectus_env_vars:
  PATH: "{{ prospectus_nodeenv_bin }}:{{ prospectus_venv_dir }}/bin:{{ ansible_env.PATH }}"
  NODE_ENV: "{{ PROSPECTUS_ENVIRONMENT }}"
  ACTIVE_ENV: "{{ PROSPECTUS_ENVIRONMENT }}"
  USE_COURSE_URL_SLUGS: "{{ PROSPECTUS_USE_COURSE_URL_SLUGS }}"
  GATSBY_CONTENTFUL_SPACE_ID: "{{ PROSPECTUS_CONTENTFUL_SPACE_ID }}"
  GATSBY_CONTENTFUL_ACCESS_TOKEN: "{{ PROSPECTUS_CONTENTFUL_ACCESS_TOKEN }}"
