# Travis CI configuration file for running tests
language: python
dist: xenial
python:
  - 3.5
  - 3.8

branches:
  only:
  - master

services:
  - docker

addons:
  apt:
    packages:
      - nodejs

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install -o Dpkg::Options::="--force-confold" docker-ce

install:
  - "pip install demjson"
  - "pip install -r requirements.txt"

env:
  global:
    - OPENEDX_RELEASE=open-release/juniper.master
    - TAG_NAME=juniper.master
  jobs:
    - MAKE_TARGET=test.syntax SHARD=0 SHARDS=1
    - MAKE_TARGET=test.playbooks SHARD=0 SHARDS=1

script:
  - docker --version
  - make --version
  - travis_wait 90 make --keep-going $MAKE_TARGET SHARD=$SHARD SHARDS=$SHARDS

deploy:
  - provider: script
    on:
      branch: jdmulloy/travis_docker_build

jobs:
  allow_failures:
    - python: 3.8
  include:
    - stage: devstack_docker_push
      name: Edxapp devstack docker image
      install: skip
      script: bash travis/docker_devstack_push.sh
      env:
        - APP_NAME=edxapp
    - name: Ecommerce devstack docker image
      install: skip
      script: bash travis/docker_devstack_push.sh
      env:
        - APP_NAME=ecommerce

stages:
  - name: test
  - name: devstack_docker_push
#    if: (NOT type IN (pull_request)) AND (branch = master)
