- name: Deploy all dependencies needed to run edx-analytics-pipeline
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    serial_count: 1
  serial: "{{ serial_count }}"
  roles:
    - analytics_pipeline
