- name: Deploy forum
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    serial_count: 1
  serial: "{{ serial_count }}"
  roles:
    - docker
    - supervisor
    - supervised_rsyslogd
    - consul
    