# Install browsermob-proxy, which is used for page performance testing with bok-choy
---

- name: install system requirements
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ browsermob_proxy_apt_requirements }}"
  tags:
    - install
    - install:system-requirements

- name: Download the latest browsermob-proxy
  get_url: 
    url: "{{ browsermob_proxy_url }}" 
    dest: "/tmp/{{ browsermob_proxy_url | basename }}"
  tags:
    - install
    - install:system-requirements

- name: install browsermob-proxy
  unarchive:
    src: "/tmp/{{ browsermob_proxy_url | basename }}"
    dest: "/etc"
    creates: "{{ browsermob_proxy_dir }}"
    copy: no
  register: download_browsermob_proxy
  tags:
    - install
    - install:system-requirements

- name: change permissions of main script
  file:
    path: "{{ browsermob_proxy_dir }}/bin/browsermob-proxy"
    mode: 0755
  when: download_browsermob_proxy.changed
  tags:
    - install
    - install:system-requirements

- name: add wrapper script /usr/local/bin/browsermob-proxy
  template:
    src: browsermob-proxy.j2
    dest: /usr/local/bin/browsermob-proxy
  when: download_browsermob_proxy.changed
  tags:
    - install
    - install:system-requirements

- name: change permissions of wrapper script
  file:
    path: /usr/local/bin/browsermob-proxy
    mode: 0755
  when: download_browsermob_proxy.changed
  tags:
    - install
    - install:system-requirements

