# When running, do pass ACCESS_KEY for appneta account as an argument to playbook e.g.
# ansible-playbook appneta.yml -i "localhost," --extra-vars "ACCESS_KEY=xxx-xx-xx"
- name: Deploy appneta
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    EDXAPP_USE_APPNETA: true
    NGINX_APT_REPO: "{{ appneta_apt_repo }}"
  roles:
    - appneta
    - edxapp
    - nginx
