# Configure a Jenkins flyweight worker instance
# This does not need to run platform tests, it will
# run only flyweight (e.g. flow) jobs.

- name: Configure instance(s)
  hosts: jenkins_worker
  become: True
  gather_facts: True
  vars:
    serial_count: 1
    COMMON_SECURITY_UPDATES: yes
    SECURITY_UPGRADE_ON_ANSIBLE: true
  serial: "{{ serial_count }}"
  roles:
    - aws
    - jenkins_worker
