# Usage: ansible-playbook splunk.yml -e@/path/to/environment-deployment.yml

- name: Deploy Splunk
  hosts: all
  become: True
  gather_facts: True
  vars:
  roles:
    - aws
    - splunk-server
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE
