---
# Installs the harprofiler
- name: create harprofiler user
  user:
    name: "{{ harprofiler_user }}"
    createhome: no
    home: "{{ harprofiler_dir }}"
    shell: /bin/bash
  tags:
    - install
    - install:base

- name: create harprofiler repo
  file:
    path: "{{ harprofiler_dir }}"
    state: directory
    owner: "{{ harprofiler_user }}"
    group: "{{ common_web_group }}"
    mode: 0755
  tags:
    - install
    - install:base

- name: check out the harprofiler
  git:
    dest: "{{ harprofiler_dir }}/harprofiler"
    repo: "{{ harprofiler_github_url }}"
    version: "{{ harprofiler_version }}"
    accept_hostkey: yes
  sudo_user: "{{ harprofiler_user }}"
  tags:
    - install
    - install:code

- name: set bashrc for harprofiler user
  template:
    src: bashrc.j2
    dest: "{{ harprofiler_dir }}/.bashrc"
    owner: "{{ harprofiler_user }}"
    mode: 0755
  tags:
    - install
    - install:configuration

- name: install system requirements
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ harprofiler_apt_requirements }}"
  tags:
    - install
    - install:system-requirements

- name: install requirements
  pip:
    requirements: "{{ harprofiler_dir }}/harprofiler/requirements.txt"
    virtualenv: "{{ harprofiler_venv_dir }}"
  sudo_user: "{{ harprofiler_user }}"
  tags:
    - install
    - install:app-requirements

- name: update config file
# harprofiler ships with a default config file. Doing a line-replace for the default
# configuration that does not match what this machine will have
  lineinfile:
    dest: "{{ harprofiler_dir }}/harprofiler/config.yaml"
    regexp: "browsermob_dir"
    line: "browsermob_dir: {{ harprofiler_browsermob_dir }}"
    state: present
  tags:
    - install
    - install:configuration

- name: create validation shell script
  template:
    owner: "{{ harprofiler_user }}"
    src: validate_harprofiler_install.sh.j2
    dest: "{{ harprofiler_dir }}/{{ harprofiler_validation_script }}"
    mode: 0755
  sudo_user: "{{ harprofiler_user }}"
  tags:
    - install
    - install:code


- name: test install
  command: "./{{ harprofiler_validation_script }}"
  args:
    chdir: "{{ harprofiler_dir }}"
  sudo_user: "{{ harprofiler_user }}"
  tags:
    - test
    - test:unit
