- name: Basic util setup on carnegie workers
# this gets all running prod webservers
# hosts: tag_environment_prod_carn:&tag_function_util
# or we can get subsets of them by name
# hosts: ~tag_Name_util(10)_carn
  hosts: ~tag_Name_util(1)_carn
  gather_facts: True
  sudo: True
  vars:
    secure_dir: '../../../edx-secret/ansible'
    # this indicates the path to site-specific (with precedence)
    # things like nginx template files
    local_dir:  '../../../../../../edx-secret/ansible/local'
    migrate_db: "no"
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_carnegie_vars.yml"
    - "{{ secure_dir }}/vars/datadog_carn.yml"
  roles:
    - role: gh_users
      gh_users:
        - sefk
        - jbau
        - jrbl
      tags: users
    - role: 'common'
      tags: common
    - role: 'supervisor'
      tags: supervisor
    - role: 'edxapp'
      celery_worker: True
      devstack: false
      tags: celery
    - datadog

## run the certificate agent on the first util machine only
#- hosts: ~tag_Name_util10_carn
#  sudo: True
#  vars:
#    secure_dir: '../../../configuration-secure/ansible'
#    migrate_db: "no"
#  vars_files:
#    - "{{ secure_dir }}/vars/edxapp_carnegie_vars.yml"
#    - "{{ secure_dir }}/vars/certifier_carn_vars.yml"
#  roles:
#    - common
#    - role: virtualenv
#      virtualenv_user: "certifier"
#      virtualenv_name: "certifier"
#      virtualenv_user_home: "/opt/wwc/certifier"
#    - certificates
