#- hosts: ~tag_Name_app(10|20)_carn
#- hosts: ~tag_Name_app10_carn
#- hosts: ~tag_Name_app20_carn
- hosts: ~tag_Name_app1_carn_test
  sudo: True
  vars_prompt:
    - name: "migrate_db"
      prompt: "Should this playbook run database migrations? (Type 'yes' to run, anything else to skip migrations)"
      default: "no"
      private: no
  vars:
    secure_dir: '../../../configuration-secure/ansible'
    # this indicates the path to site-specific (with precedence)
    # things like nginx template files
    #local_dir:  '../../../edx-secret/ansible/local'
    local_dir: "{{secure_dir}}/local"
    # this toggles http basic auth on and off. false in production
    not_prod: false
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_carnegie_vars.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/edxapp_prod_users.yml"
    - "{{ secure_dir }}/vars/datadog_carn.yml"
  roles:
    - role: gh_users
      gh_users:
        - sefk
        - jbau
        - jrbl
      tags: users
    - common
    - supervisor
    - php
    - role: nginx
      nginx_sites:
      - lms
      - cms
      - lms-preview
      - phpmyadminc
      nginx_template_directory: "{{local_dir}}/nginx/templates/carnegie/"
      nginx_conf: true
    - {'role': 'edxapp', 'openid_workaround': true, 'template_subdir': 'carnegie'}
    - datadog
    #- splunkforwarder
    # run this role last
    # - in_production
