
# set up the fireball transport
#- hosts: ~tag_Name_app(10|20)_cme
#  gather_facts: no
#  connection: ssh # or paramiko
#  sudo: yes
#  tasks:
#      - apt: pkg=gcc state=present
#      - apt: pkg=libzmq-dev,python-zmq state=present
#      - action: fireball


# this gets all running prod webservers
#- hosts: tag_environment_prod:&tag_function_webserver
# or we can get subsets of them by name
#- hosts: ~tag_Name_app(1|2)_cme
- hosts: ~tag_Name_app1_cme
#- hosts: ~tag_Name_app2_cme
#- hosts: ~tag_Name_app(1|2)_cme
  sudo: True
  vars_prompt:
    - name: "migrate_db"
      prompt: "Should this playbook run database migrations? (Type 'yes' to run, anything else to skip migrations)"
      default: "no"
      private: no
  vars:
    secure_dir: '../../../edx-secret/ansible'
    # this indicates the path to site-specific (with precedence)
    # things like nginx template files
    local_dir:  '{{ secure_dir }}/local'
    not_prod: true
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_cme_vars.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/edxapp_prod_users.yml"
    - "{{ secure_dir }}/vars/datadog_cme.yml"
  roles:
    #- ansible_debug
    - role: gh_users
      gh_users:
        - sefk
        - jbau
        - jrbl
        - caesar2164
        - nparlante
      tags: users
    - common
    - supervisor
    - role: nginx
      nginx_conf: true
      nginx_sites:
      - lms
      - cms
      nginx_template_directory: "{{local_dir}}/nginx/templates/cme/"
    - {'role': 'edxapp', 'openid_workaround': true, 'template_subdir': 'cme'}
    - datadog
    #- splunkforwarder
    # run this role last
    # - in_production
