# this gets all running prod webservers
#- hosts: tag_environment_prod:&tag_function_webserver
# or we can get subsets of them by name
#- hosts: ~tag_Name_app1_prod
- hosts: ~tag_Name_app2_prod
## this is the test box
#- hosts: ~tag_Name_app4_prod
#- hosts: ~tag_Name_app(4|1|2)_prod
## you can also do security group, but don't do that
#- hosts: security_group_edx-prod-EdxappServerSecurityGroup-NSKCQTMZIPQB
  sudo: True
  vars_prompt:
    - name: "migrate_db"
      prompt: "Should this playbook run database migrations? (Type 'yes' to run, anything else to skip migrations)"
      default: "no"
      private: no
  vars:
    secure_dir: '../../../configuration-secure/ansible'
    # this indicates the path to site-specific (with precedence)
    # things like nginx template files
    local_dir:  '../../../configuration-secure/ansible/local'
    not_prod: false
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_prod_vars.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/edxapp_prod_users.yml"
    - "{{ secure_dir }}/vars/shib_prod_vars.yml"
    - "{{ secure_dir }}/vars/datadog_prod.yml"
  roles:
    - role: gh_users
      gh_users:
        - sefk
        - jbau
        - jrbl
        - caesar2164
        - nparlante
      tags: users
    - common
    - supervisor
    - role: nginx
      nginx_sites:
      - lms
      - lms-preview
      - cms
      - verify
      nginx_template_directory: "{{local_dir}}/nginx/templates/"
      tags: nginx
    - edxapp
    - apache
    - shibboleth
    - datadog
    #- splunkforwarder
    # run this role last
    #- in_production
