- name: Basic util setup on all hosts
#- hosts: tag_environment_stage:&tag_function_util
  hosts: ~tag_Name_util1_stage
  sudo: True
  gather_facts: True
  vars:
    secure_dir: ../../../edx-secret/ansible
    local_dir: "{{secure_dir}}/local"
    migrate_db: "no"
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_stage_vars.yml"
    - "{{ secure_dir }}/vars/xqueue_stage_vars.yml"
    #- "{{ secure_dir }}/vars/users.yml"
    #- "{{ secure_dir }}/vars/edxapp_stage_users.yml"
    - "{{ secure_dir }}/vars/datadog_stage.yml"
  roles:
    - role: 'common'
      tags: common
    - role: 'supervisor'
      tags: supervisor
    - role: gh_users
      gh_users:
      - sefk
      - jbau
      - jrbl
      - ali123
      - dcadams
      - caesar2164
      - jinpa
      - gbruhns
      tags: users
    - role: 'edxapp'
      celery_worker: True
      devstack: false
      tags: celery
    - role: nginx
      nginx_sites:
      - xqueue
      - basic-auth
      tags: nginx
    - role: xqueue
      xqueue_create_db: "no"
      xqueue_create_users: false
      tags: xqueue

#- name: Deploy certs, notifier only to first util machine
  hosts: ~tag_Name_util1_stage
  sudo: True
  gather_facts: True
  vars:
    secure_dir: '../../../configuration-secure/ansible'
    local_dir: "{{secure_dir}}/local"
    migrate_db: "no"
  vars_files:
    - "roles/common/defaults/main.yml"
    - "roles/supervisor/defaults/main.yml"
    - "{{ secure_dir }}/vars/edxapp_stage_vars.yml"
    - "{{ secure_dir }}/vars/certs_stage_vars.yml"
  roles:
    - role: gh_users # gh_users var intentionally unspecified
      tags: users 
    - role: certs
      tags: certs

#- name: Deploy certs to first util machine
#  hosts: ~tag_Name_util1_stage
#  sudo: True
#  vars:
#    secure_dir: '../../../configuration-secure/ansible'
#    migrate_db: "no"
#  vars_files:
#    - "{{ secure_dir }}/vars/edxapp_stage_vars.yml"
#    - "{{ secure_dir }}/vars/certifier_stage_vars.yml"
#  roles:
#    - common
#    - role: virtualenv
#      virtualenv_user: "certifier"
#      virtualenv_name: "certifier"
#      virtualenv_user_home: "/opt/wwc/certifier"
#    - certificates
