# This uses variable expansion so you can select machine(s) from the command line
# using the -e flag.  See README for instructions on how to use.
- hosts: ~tag_Name_{{machine}}_stage
#
# This alternative hits all running prod webservers.  Left here as an example.
#- hosts: tag_environment_stage:&tag_function_webserver
  sudo: True
  vars_prompt:
    - name: "migrate_db"
      prompt: "Should this playbook run database migrations? (Type 'yes' to run, anything else to skip migrations)"
      default: "no"
      private: no
  vars:
    not_prod: true
    secure_dir: "../../../edx-secret/ansible"
    local_dir: "{{secure_dir}}/local"
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_stage_vars.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/edxapp_stage_users.yml"
    - "{{ secure_dir }}/vars/shib_stage_vars.yml"
    #- "{{ secure_dir }}/vars/datadog_stage.yml"
  roles:
    - common
    - supervisor
    - role: gh_users
      gh_users:
        - sefk
        - jbau
        - jrbl
        - ali123
        - caesar2164
        - dcadams
        - nparlante
        - jarv
        - e0d
        - feanil
      gh_users_no_sudo:
        - jinpa
        - gbruhns
      tags: users
    - role: nginx
      nginx_sites:
      - lms
      - cms
      - verify
      nginx_template_directory: "{{local_dir}}/nginx/templates/"
    - role: edxapp
      devstack: false
    - apache
    - shibboleth
    #- datadog
    #- splunkforwarder

    
