---
# The deadsnakes PPA is required to install python3.5 on Trusty.
# Xenial comes with python3.5 installed.
- name: add deadsnakes repository
  apt_repository:
    repo: "ppa:deadsnakes/ppa"
  when: ansible_distribution_release == 'trusty'
  tags:
    - install
    - install:system-requirements

- name: "install python3.5 to 3.9"
  apt:
    name: "{{ item }}"
  with_items:
    - python3.5
    - python3.5-dev
    - python3.6
    - python3.6-dev
    - python3.7
    - python3.7-dev
    - python3.8
    - python3.8-dev
    - python3.9
    - python3.9-dev
  when: ansible_distribution_release == 'trusty'
  tags:
    - install
    - install:system-requirements
