---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role discovery
#
# Overview: This role's tasks come from edx_django_service.
#
#
# Dependencies:
#
#
# Example play:
#
#
- name: create web-writable journal data dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ common_web_user }}"
    group: "{{ journals_user }}"
    mode: "0775"
  with_items:
    - "{{ JOURNALS_MEDIA_ROOT }}"
  tags:
    - install
    - install:base
