---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
# Includes for role video_worker.
#

dependencies:
  - common
  - supervisor
  - role: edx_service
    edx_service_name: "{{ video_worker_service_name }}"
    edx_service_config: "{{ VIDEO_WORKER_SERVICE_CONFIG }}"
    edx_service_repos: "{{ VIDEO_WORKER_REPOS }}"
    edx_service_user: "{{ video_worker_user }}"
    edx_service_home: "{{ video_worker_home }}"
    edx_service_packages:
      debian: "{{ video_worker_debian_pkgs }}"
  - role: video_common_vars
    video_common_service_name: '{{ video_worker_service_name }}'
    video_common_veda_url_root: '{{ VIDEO_PIPELINE_URL_ROOT }}'
    video_common_val_base_url: '{{ VAL_BASE_URL }}'

    # We need these values from video-pipeline so that video-worker can communicate with it.
    video_common_social_auth_edx_oidc_key: '{{ VIDEO_PIPELINE_SOCIAL_AUTH_EDX_OIDC_KEY }}'
    video_common_social_auth_edx_oidc_secret: '{{ VIDEO_PIPELINE_SOCIAL_AUTH_EDX_OIDC_SECRET }}'
    video_common_veda_api_url: '{{ VIDEO_PIPELINE_API_URL }}'
    video_common_veda_oauth_url: '{{ VIDEO_PIPELINE_OAUTH_URL }}'
    video_common_veda_oauth_token_url: '{{ VIDEO_PIPELINE_OAUTH_TOKEN_URL }}'
    video_common_veda_oauth_client_id: '{{ VIDEO_PIPELINE_OAUTH_CLIENT_ID }}'
    video_common_veda_oauth_client_secret: '{{ VIDEO_PIPELINE_OAUTH_CLIENT_SECRET }}'

    video_common_rabbitmq_broker: '{{ VIDEO_WORKER_RABBITMQ_BROKER }}'
    video_common_rabbitmq_user: '{{ VIDEO_WORKER_RABBITMQ_USER }}'
    video_common_rabbitmq_pass: '{{ VIDEO_WORKER_RABBITMQ_PASS }}'
