---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
# Includes for role video_worker.
#

dependencies:
  - common
  - supervisor
  - role: edx_service
    edx_service_name: "{{ video_worker_service_name }}"
    edx_service_config: "{{ VIDEO_WORKER_SERVICE_CONFIG }}"
    edx_service_repos: "{{ VIDEO_WORKER_REPOS }}"
    edx_service_user: "{{ video_worker_user }}"
    edx_service_home: "{{ video_worker_home }}"
    edx_service_packages:
      debian: "{{ video_worker_debian_pkgs }}"
