---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
# Defaults for role video_worker.
#


video_worker_service_name: 'video_worker'
video_worker_user: '{{ video_worker_service_name }}'
video_worker_home: '{{ COMMON_APP_DIR }}/{{ video_worker_service_name }}'
video_worker_code_dir: '{{ video_worker_home }}/{{ video_worker_service_name }}'
video_worker_venv: '{{ video_worker_home }}/venvs/{{ video_worker_service_name }}'
video_worker_venv_bin: '{{ video_worker_home }}/venvs/{{ video_worker_service_name }}/bin'
video_worker_log_dir: '{{ COMMON_LOG_DIR }}/{{ video_worker_service_name }}'

video_worker_environment:
  PATH: '{{ video_worker_venv_bin }}:{{ ansible_env.PATH }}'
  VIDEO_WORKER_CFG: "{{ COMMON_CFG_DIR }}/{{ video_worker_service_name }}.yml"
  PYTHONPATH: "{{ video_worker_code_dir }}"

VIDEO_WORKER_GIT_IDENTITY: !!null
VIDEO_WORKER_VERSION: 'master'

VIDEO_WORKER_REPOS:
  - PROTOCOL: '{{ COMMON_GIT_PROTOCOL }}'
    DOMAIN: '{{ COMMON_GIT_MIRROR }}'
    PATH: '{{ COMMON_GIT_PATH }}'
    REPO: edx-video-worker.git
    VERSION: '{{ VIDEO_WORKER_VERSION }}'
    DESTINATION: '{{ video_worker_code_dir }}'
    SSH_KEY: '{{ VIDEO_WORKER_GIT_IDENTITY }}'

# Requires that New Relic be enabled via COMMON_ENABLE_NEWRELIC, and that
# a key be provided via NEWRELIC_LICENSE_KEY.
VIDEO_WORKER_NEWRELIC_APPNAME: '{{ COMMON_ENVIRONMENT }}-{{ COMMON_DEPLOYMENT }}-{{ video_worker_service_name }}'

VIDEO_WORKER_BROKER_USERNAME: 'video-worker'
VIDEO_WORKER_BROKER_PASSWORD: 'video-worker'
VIDEO_WORKER_BROKER_HOST: 'localhost'

VIDEO_WORKER_CONCURRENCY: 'SET-ME-PLEASE'
VIDEO_WORKER_QUEUES: 'SET-ME-PLEASE'

# OS packages
VIDEO_WORKER_DEBIAN_PKGS: ['ffmpeg']
