---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
# Defaults for role video_worker.
#

VIDEO_WORKER_GIT_IDENTITY: !!null
VIDEO_WORKER_VERSION: 'master'

VIDEO_WORKER_REPOS:
  - PROTOCOL: '{{ COMMON_GIT_PROTOCOL }}'
    DOMAIN: '{{ COMMON_GIT_MIRROR }}'
    PATH: '{{ COMMON_GIT_PATH }}'
    REPO: edx-video-worker.git
    VERSION: '{{ VIDEO_WORKER_VERSION }}'
    DESTINATION: '{{ video_worker_code_dir }}'
    SSH_KEY: '{{ VIDEO_WORKER_GIT_IDENTITY }}'

# Requires that New Relic be enabled via COMMON_ENABLE_NEWRELIC, and that
# a key be provided via NEWRELIC_LICENSE_KEY.
VIDEO_WORKER_NEWRELIC_APPNAME: '{{ COMMON_ENVIRONMENT }}-{{ COMMON_DEPLOYMENT }}-{{ video_worker_service_name }}'

VIDEO_WORKER_BROKER_USERNAME: 'celery'
VIDEO_WORKER_BROKER_PASSWORD: 'celery'
# Used as the default RabbitMQ IP.
VIDEO_WORKER_BROKER_HOST: '{{ ansible_default_ipv4.address }}'
# Used as the default RabbitMQ port.
VIDEO_WORKER_BROKER_PORT: 5672
VIDEO_WORKER_BROKER_URL: 'amqp://{{ VIDEO_WORKER_BROKER_USERNAME }}:{{ VIDEO_WORKER_BROKER_PASSWORD }}@{{ VIDEO_WORKER_BROKER_HOST }}:{{ VIDEO_WORKER_BROKER_PORT }}'
VIDEO_WORKER_CONCURRENCY: 4

video_worker_environment:
  WORKER_CONFIGURATION_MODULE: 'video_worker.configuration.production'
  video_worker_cfg: '{{ COMMON_CFG_DIR }}/{{ video_worker_service_name }}.yml'

video_worker_service_name: 'video_worker'
video_worker_user: '{{ video_worker_service_name }}'
video_worker_home: '{{ COMMON_APP_DIR }}/{{ video_worker_service_name }}'
video_worker_code_dir: '{{ video_worker_home }}/{{ video_worker_service_name }}'

video_worker_log_dir: '{{ COMMON_LOG_DIR }}/{{ video_worker_service_name }}'

video_worker_requirements_base: '{{ video_worker_code_dir }}/requirements'
video_worker_requirements:
  - production.txt
  - optional.txt

# OS packages
video_worker_debian_pkgs: []oe
video_worker_redhat_pkgs: []
