---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
# Defaults for role video_worker.
#


video_worker_service_name: 'video_worker'
video_worker_user: '{{ video_worker_service_name }}'
video_worker_home: '{{ COMMON_APP_DIR }}/{{ video_worker_service_name }}'
video_worker_code_dir: '{{ video_worker_home }}/{{ video_worker_service_name }}'
video_worker_venv: '{{ video_worker_home }}/venvs/{{ video_worker_service_name }}'
video_worker_venv_bin: '{{ video_worker_home }}/venvs/{{ video_worker_service_name }}/bin'
video_worker_log_dir: '{{ COMMON_LOG_DIR }}/{{ video_worker_service_name }}'

video_worker_environment:
  PATH: '{{ video_worker_venv_bin }}:{{ ansible_env.PATH }}'
  VIDEO_WORKER_CFG: "{{ COMMON_CFG_DIR }}/{{ video_worker_service_name }}.yml"
  PYTHONPATH: "{{ video_worker_code_dir }}"

VIDEO_WORKER_GIT_IDENTITY: !!null
VIDEO_WORKER_VERSION: 'master'

VIDEO_WORKER_REPOS:
  - PROTOCOL: '{{ COMMON_GIT_PROTOCOL }}'
    DOMAIN: '{{ COMMON_GIT_MIRROR }}'
    PATH: '{{ COMMON_GIT_PATH }}'
    REPO: edx-video-worker.git
    VERSION: '{{ VIDEO_WORKER_VERSION }}'
    DESTINATION: '{{ video_worker_code_dir }}'
    SSH_KEY: '{{ VIDEO_WORKER_GIT_IDENTITY }}'

# Requires that New Relic be enabled via COMMON_ENABLE_NEWRELIC, and that
# a key be provided via NEWRELIC_LICENSE_KEY.
VIDEO_WORKER_NEWRELIC_APPNAME: '{{ COMMON_ENVIRONMENT }}-{{ COMMON_DEPLOYMENT }}-{{ video_worker_service_name }}'

VIDEO_WORKER_RABBITMQ_BROKER: "localhost"
VIDEO_WORKER_RABBITMQ_USER: "video_worker"
VIDEO_WORKER_RABBITMQ_PASS: "video_worker"

VIDEO_WORKER_CONCURRENCY: 'SET-ME-PLEASE'
VIDEO_WORKER_QUEUES: 'SET-ME-PLEASE'

# OS packages
VIDEO_WORKER_DEBIAN_PKGS: ['ffmpeg']

# TODO: We need these values from video-pipeline so that video-worker can communicate with it.
# Temporarily placed here for testing
VIDEO_PIPELINE_SOCIAL_AUTH_EDX_OIDC_KEY: "pipeline-key"
VIDEO_PIPELINE_SOCIAL_AUTH_EDX_OIDC_SECRET: "pipeline-secret"
VIDEO_PIPELINE_API_URL: "{{ VIDEO_PIPELINE_URL_ROOT }}/api"
VIDEO_PIPELINE_OAUTH_URL: "{{ VIDEO_PIPELINE_URL_ROOT }}/veda_auth"
VIDEO_PIPELINE_OAUTH_TOKEN_URL: "{{ VIDEO_PIPELINE_URL_ROOT }}/o/token"
VIDEO_PIPELINE_OAUTH_CLIENT_ID: "video-pipeline-client-id"
VIDEO_PIPELINE_OAUTH_CLIENT_SECRET: "video-pipeline-client-secret"
