
---
##
# Defaults for role threatstack
#
THREATSTACK_REPO: 'https://pkg.threatstack.com'
THREATSTACK_KEY_URL: 'https://app.threatstack.com/APT-GPG-KEY-THREATSTACK'
# Number of rotated file "/opt/threatstack/cloudsight/logs/tsaudit.log" to keep
THREATSTACK_LOGS_TO_KEEP: '2'
# Maximum log file size before rotate in MB
THREATSTACK_LOGS_MAX_SIZE: 100
threatstack_log_dir: "/opt/threatstack/cloudsight/logs"
