- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  serial: 10
  vars:
    migrate_db: "yes"
  roles:
    - aws
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - xqueue
      - xserver
      nginx_default_sites:
      - lms
    - mysql
    - role: edxlocal
      tags: edxlocal
    - memcache
    - mongo_3_2
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - role: hermes
      when: "EDXAPP_HERMES_ENABLED"
      hermes_allowed_sudo_commands:
        - "/bin/cp {{ hermes_download_dir }}/lms.yml {{ COMMON_CFG_DIR }}/lms.yml"
        - "/bin/cp {{ hermes_download_dir }}/lms.yml {{ COMMON_CFG_DIR }}/cms.yml"
        - "/edx/bin/supervisorctl restart"
      hermes_service_config:
        - url: '{{ HERMES_REMOTE_FILE_LOCATION }}/{{ COMMON_ENVIRONMENT }}/lms.yml'
          filename: '{{ hermes_download_dir }}/lms.yml'
          command:  "sudo /bin/cp {{ hermes_download_dir }}/lms.yml {{ COMMON_CFG_DIR }}/lms.yml && /edx/bin/supervisorctl restart"
        - url: '{{ HERMES_REMOTE_FILE_LOCATION }}/{{ COMMON_ENVIRONMENT }}/cms.yml'
          filename: '{{ hermes_download_dir }}/cms.yml'
          command:  "sudo /bin/cp {{ hermes_download_dir }}/cms.yml {{ COMMON_CFG_DIR }}/cms.yml && /edx/bin/supervisorctl restart"
    - testcourses
    - role: redis
    - oraclejdk
    - elasticsearch
    - forum
    - { role: notifier, NOTIFIER_DIGEST_TASK_INTERVAL: "5" }
    - { role: "xqueue", update_users: True }
    - role: xserver
      when: XSERVER_GIT_IDENTITY|length > 0
    - edx_ansible
    - analytics_api
    - ecommerce
    - credentials
    - discovery
    - role: journals
      when: JOURNALS_ENABLED
    - oauth_client_setup
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: datadog-uninstall
      when: not COMMON_ENABLE_DATADOG
    - flower
