---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
# Tasks for role portal.
# 

- name: install node dependencies
  shell: "{{ portal_nodeenv_bin }}/npm install"
  args:
    chdir: "{{ portal_code_dir }}"
  become_user: "{{ portal_user }}"
  environment: "{{ portal_environment }}"
  tags:
    - install
    - install:app-requirements

- name: build the static application
  shell: "{{ portal_nodeenv_bin }}/npm build"
  args:
    chdir: "{{ portal_code_dir }}"
  become_user: "{{ portal_user }}"
  environment: "{{ portal_environment }}"
  tags:
    - install
    - install:app-requirements
