jenkins_home: "{{ COMMON_DATA_DIR }}/jenkins"
jenkins_user: "jenkins"
jenkins_group: "edx"
jenkins_server_name: "spigot.testeng.edx.org"
jenkins_port: 8080
jenkins_nginx_port: 80
jenkins_protocol_https: true

jenkins_version: "1.638"
jenkins_deb_url: "http://pkg.jenkins-ci.org/debian/binary/jenkins_{{ jenkins_version }}_all.deb"
jenkins_deb: "jenkins_{{ jenkins_version }}_all.deb"
# Jenkins jvm args are set when starting the Jenkins service, e.g., "-Xmx1024m"
jenkins_jvm_args: ""

jenkins_debian_pkgs:
    - nginx
    - git
    - maven
    - daemon
    - python-pycurl
    - psmisc

# Extra packages need for a specific jenkins instance.
JENKINS_EXTRA_PKGS: []
